api_root/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('finance.urls')),
]

finance/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import Index, PersonList, PersonCreate, PersonUpdate, PersonDelete, BillList, BillCreate, BillUpdate, BillDelete 

app_name = 'finance'

urlpatterns = [
    path('index/', Index.as_view(), name='index'),

    path('person_list/', PersonList.as_view(), name='person'),
    path('person_create/', PersonCreate.as_view(), name='person_create'),
    path('person_update/<int:pk>/', PersonUpdate.as_view(), name='person_update'),
    path('person_delete/<int:pk>/', PersonDelete.as_view(), name='person_delete'),

    path('bill_list/', BillList.as_view(), name='bill'),
    path('bill_create/', BillCreate.as_view(), name='bill_create'),
    path('bill_update/<int:pk>/', BillUpdate.as_view(), name='bill_update'),
    path('bill_delete/<int:pk>/', BillDelete.as_view(), name='bill_delete'),
]

financas/models.py
from sqlalchemy import Column, Integer, String, Float

from database import Base

class Person(Base):
    __tablename__ = "person"

    id: int = Column(Integer, primary_key=True, index=True)
    name: str = Column(String(255), nullable=False)
    income: float = Column(Float, nullable=False)

class Bill(Base):
    __tablename__ = "bill"

    id: int = Column(Integer, primary_key=True, index=True)
    name: str = Column(String(255), nullable=False)
    price: float = Column(Float, nullable=False)

finance/models.py
from django.db import models

class Person(models.Model):
    name = models.CharField(max_length=120, verbose_name='Nome', blank=False, null=False)
    doc = models.IntegerField(verbose_name='CPF', blank=False, null=False)
    income = models.FloatField(verbose_name='Renda', blank=False, null=False)

    def __str__(self):
        return f'Nome:{self.name}'



class Bill(models.Model):
    name = models.CharField(max_length=120, verbose_name='Nome', blank=False, null=False)
    price = models.FloatField(verbose_name='Valor', blank=False, null=False)
    due_date = models.DateField(verbose_name='Vencimento', blank=False, null=False)


    def __str__(self):
        return f'Nome:{self.name}'

finance/forms.py
import django.forms as forms
from .models import Person, Bill


class PersonForm(forms.ModelForm):
    
    class Meta:
        model = Person
        fields = ['name', 'doc', 'income']

class BillForm(forms.ModelForm):
    
    class Meta:
        model = Bill
        fields = ['name', 'price', 'due_date']

financas/views.py
from django.shortcuts import render

# Create your views here.

finance/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .models import Person, Bill
from .forms import PersonForm, BillForm


class Index(ListView):
    model=Person
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['finance_data'] = self.get_finance_data()
        return context

    def get_finance_data(self):
        # Obtém as todas as pessoas
        people = Person.objects.all()
        finance_data = []

        total_income = 0
        total_people = 0
        for person in people:
            total_income+= person.income
            total_people+=1

        total_bills = 0

        bills = Bill.objects.all()
        for bill in bills:
            total_bills+= bill.price
        net_income = total_income - total_bills

        finance_data.append({
            'total_income': round(total_income, 2),
            'total_people': total_people,
            'total_bill': round(total_bills, 2),
            'net_income': round(net_income, 2),
                             })

        return finance_data
    

class PersonList(ListView):
    model = Person
    template_name = 'person.html'

    
class PersonCreate(CreateView):
    model = Person
    template_name = 'person_create.html'
    success_url = reverse_lazy('finance:person')
    form_class = PersonForm

    def form_valid(self, form):
        return super().form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super(PersonCreate, self).get_form_kwargs()
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class PersonUpdate(UpdateView):
    model = Person
    template_name = 'person_update.html'
    fields = ['name', 'doc', 'income']
    success_url = reverse_lazy('finance:person')


class PersonDelete(DeleteView):
    model = Person
    template_name = 'person_delete.html'
    
    def get_success_url(self):
        return reverse_lazy("finance:person")
    

class BillList(ListView):
    model = Bill
    template_name = 'bill.html'


class BillCreate(CreateView):
    model = Bill
    template_name = 'bill_create.html'
    success_url = reverse_lazy('finance:bill')
    form_class = BillForm

    def form_valid(self, form):
        return super().form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super(BillCreate, self).get_form_kwargs()
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context  


class BillUpdate(UpdateView):
    model = Bill
    template_name = 'bill_update.html'
    fields = ['name', 'price', 'due_date']
    success_url = reverse_lazy('finance:bill')


class BillDelete(DeleteView):
    model = Bill
    template_name = 'bill_delete.html'
    
    def get_success_url(self):
        return reverse_lazy("finance:bill")

finance/templates/bill.html
<style>
    *{
    margin: 0;
    padding: 0;
    }
    body{
        width: 100%;
        height: 100%;
        font-family: 'Poppins', sans-serif;
        background: linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
    }
    .title{
        font-size: 1.8em;
        margin-bottom: 10%;
    }
    .th,td{
        width: min-content;
        border-radius: 22px;
        border: 2px #fff solid;
        padding: 5px;
        margin: 2px 2px 12px -5px;
    }
    .footer {
    font-family: 'Arial', sans-serif;
    background-color: #e5e5e5; /* Altere a cor conforme necessário */
    color: #333;
    text-align: center;
    padding: 10px 0;
    position: fixed;
    bottom: 0;
    width: 100%;
  }
  .navbar-header {
    font-family: 'Arial', sans-serif;
    background-color:transparent; /* Cor de fundo cinza escuro */
    color: #fff; /* Cor do texto branco */
    padding: 20px; /* Espaçamento interno */
  }
  .navbar-menu-header a {
    color: #fff; /* Cor do texto branco */
    margin-right: 20px; /* Espaçamento entre os itens do menu */
    text-decoration: none; /* Remover sublinhado dos links */
    font-weight: bold; /* Negrito para destacar os links */
  }
  .table{
    text-align: center;
  }
</style>
  
<header class="navbar navbar-header navbar-header-fixed">
    <div class="container-fluid">
      <a href="" id="mainMenuOpen" class="burger-menu"><i data-feather="menu"></i></a>
      <div id="navbarMenu" class="navbar-menu-wrapper">
        <div class="navbar-menu-header">
            <a href="{% url 'finance:index' %}" class="df-logo"><span>Home</span></a>
            <a href="{% url 'finance:person' %}" class="df-logo"><span>Pessoas</span></a>
            <a href="{% url 'finance:bill' %}"><span>Contas</span></a>
            <a href="{% url 'finance:person_create' %}" class="df-logo"><span>Cadastrar Pessoa</span></a>
            <a href="{% url 'finance:bill_create' %}" class="df-logo"><span>Cadastrar Conta</span></a>
        </div>
      </div> 
    </div>
</header>

<body>
    {% block content %}
    <div id="table" class="full-width">
            
        <table class="table">
            <thead class="body-title">
                <tr class= "bg-gray-200 p-2">
                    <th>Nome</th>
                    <th>Valor</th>
                    <th>Data de Vencimento</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for item in object_list %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>R$ {{ item.price }}</td>
                    <td>{{ item.due_date }}</td>
                    <td class="action-cell">
                        <a class="btn btn-warning"title="Editar"
                            href="{% url 'finance:bill_update' item.id %}">Editar
                        </a>
                        <a class="btn btn-danger"title="Deletar"
                            href="{% url 'finance:bill_delete' item.id %}" style="margin-left: 15px;">Deletar
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div id="btn">
            <a class="btn btn-secondary" style="margin-left: 10px" href="{% url 'finance:index' %}">Voltar</a>
        </div>
    </div>
    {% endblock content %}
</body>
   
<div id="map"></div>
<footer class="footer bg-info">
    <div class="w-100">
    <span>&copy; 2024 Camilla Pinto  </span>
    </div>
</footer>

finance/templates/bill_create.html
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght0600&display=swap');
    *{
    margin: 0;
    padding: 0;
    }
    body{
        width: 100%;
        height: 100%;
        font-family: 'Poppins', sans-serif;
        background: linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
    }
    #form{
        position: relative;
        top: 25%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: #fff ;
        border-radius: 10px ;
        padding: 60px;
        width: min-content;
        align-items: center;
        color: #2b344b;
    }
    .title{
        font-size: 1.8em;
        margin-bottom: 10%;
    }
    .input{
        min-width: 280px;
        border-radius: 22px;
        border: 2px #6f7e8a dashed;
        padding: 5px;
        margin: 0px 0px 12px -5px;
    }
    .input i{
        font-size: 1.2em;
        padding: 5px;
        background: -webkit-linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
        -webkit-background-clip: text;
        -webkit-text-fill-color:#fff ;
    }
    .input input{
        width: 80%;
        border: none;
        outline: none;
        font-family: 'Poppins', sans-serif;
        transform: translateY(-10%);
        color: #2b344b ;
        font-size: 11pt ;
    }
    #btn{
        margin-top: 10%;
        width: 100%;
        text-align: center;
    }
    #btn button{
        font-family: 'Poppins';
        background: linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
        width: 100% ;
        height: 40px;
        border: none;
        font-size: 11pt;
        color: #fff;
        border-radius: 20px;
        outline: none;
        cursor: pointer;
    }
    
</style>

<head>
    <script src="https://kit.fontawesome.com/948cd96e81.js" crossorigin="anonymous"></script>
</head>
<body>
    <div>
        <form method="post" action="{% url 'finance:bill_create' %}">
            {% csrf_token %}
            <h2 class="title">Cadastrar Conta</h2>
            <label for="name" style="color: #fff;">Nome</label>
            <div class="input">
                <i class="fa-regular fa-user"></i>
                <input type="text" name="name" id="name" placeholder="Nome da Empresa" required>
            </div>
            <label for="price" style="color: #fff;">Valor</label>
            <div class="input">
                <i class="fa-solid fa-id-card"></i>
                <input type="text" name="price" id="price" placeholder="Insira valor da fatura" required>
            </div>
            <label for="due_date" style="color: #fff;">Data de Vencimento</label>
            <div class="input">
                <i class="fa-solid fa-sack-dollar"></i>
                <input type="date" name="due_date" id="due_date" required>
            </div>
            <div id="btn">
                <a class="btn btn-secondary" style="color: #fff;" href="{% url 'finance:index' %}">Voltar</a>
                <button type="submit">Salvar</button>
            </div>
        </form>
    </div>
</body>

finance/templates/bill_delete.html
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght0600&display=swap');
    *{
    margin: 0;
    padding: 0;
    }
    body{
        width: 100%;
        height: 100%;
        font-family: 'Poppins', sans-serif;
        background: linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
    }
    #form{
        position: relative;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: #fff ;
        border-radius: 10px ;
        padding: 60px;
        width: min-content;
        align-items: center;
        color: #2b344b;
    }
    .title{
        font-size: 1.8em;
        margin-bottom: 10%;
    }
    .input{
        min-width: 280px;
        border-radius: 22px;
        border: 2px #6f7e8a dashed;
        padding: 5px;
        margin: 0px 0px 12px -5px;
    }
    .input i{
        font-size: 1.2em;
        padding: 5px;
        background: -webkit-linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
        -webkit-background-clip: text;
        -webkit-text-fill-color:transparent ;
    }
    .input input{
        width: 80%;
        border: none;
        outline: none;
        font-family: 'Poppins', sans-serif;
        transform: translateY(-10%);
        color: #2b344b ;
        font-size: 11pt ;
    }
    #btn{
        margin-top: 10%;
        width: 100%;
        text-align: center;
    }
    #btn button{
        font-family: 'Poppins';
        background: linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
        width: 100% ;
        height: 40px;
        border: none;
        font-size: 11pt;
        color: #2b344b;
        border-radius: 20px;
        outline: none;
        cursor: pointer;
    }
    
</style>

<head>
    <script src="https://kit.fontawesome.com/948cd96e81.js" crossorigin="anonymous"></script>
    <title>Cadastro de Pessoa</title>
</head>
<body>
    <div>
        
            <h2 class="title">Confirmar Exclusão</h2>
            <label for="name">Nome</label>
            <div class="input">
                <i class="fa-regular fa-user"></i>
                <input type="text" name="name" id="name" value="{{ object.name }}" readonly>
            </div>
            <label for="price">Valor</label>
            <div class="input">
                <i class="fa-solid fa-id-card"></i>
                <input type="text" name="price" id="price" value="{{ object.price }}" readonly>
            </div>
            <label for="due_date">Data de Vencimento</label>
            <div class="input">
                <i class="fa-solid fa-sack-dollar"></i>
                <input type="text" name="due_date" id="due_date" value="{{ object.due_date }}" readonly>
            </div>
            <div id="btn">
                <a class="btn btn-secondary" href="{% url 'finance:index' %}">Voltar</a>
                <form method="post" action="{% url 'finance:bill_delete' object.id %}">
                    {% csrf_token %}
                <button type="submit">Confirmar</button>
                </form>
            </div>
        
    </div>
</body>

finance/templates/bill_update.html
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght0600&display=swap');
    *{
    margin: 0;
    padding: 0;
    }
    body{
        width: 100%;
        height: 100%;
        font-family: 'Poppins', sans-serif;
        background: linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
    }
    #form{
        position: relative;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: #fff ;
        border-radius: 10px ;
        padding: 60px;
        width: min-content;
        align-items: center;
        color: #2b344b;
    }
    .title{
        font-size: 1.8em;
        margin-bottom: 10%;
    }
    .input{
        min-width: 280px;
        border-radius: 22px;
        border: 2px #6f7e8a dashed;
        padding: 5px;
        margin: 0px 0px 12px -5px;
    }
    .input i{
        font-size: 1.2em;
        padding: 5px;
        background: -webkit-linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
        -webkit-background-clip: text;
        -webkit-text-fill-color:transparent ;
    }
    .input input{
        width: 80%;
        border: none;
        outline: none;
        font-family: 'Poppins', sans-serif;
        transform: translateY(-10%);
        color: #2b344b ;
        font-size: 11pt ;
    }
    #btn{
        margin-top: 10%;
        width: 100%;
        text-align: center;
    }
    #btn button{
        font-family: 'Poppins';
        background: linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
        width: 100% ;
        height: 40px;
        border: none;
        font-size: 11pt;
        color: #2b344b;
        border-radius: 20px;
        outline: none;
        cursor: pointer;
    }
    
</style>

<head>
    <script src="https://kit.fontawesome.com/948cd96e81.js" crossorigin="anonymous"></script>
    <title>Cadastro de Conta</title>
</head>
<body>
    <div>
        <form method="post" action="{% url 'finance:bill_update' object.id %}">
            {% csrf_token %}
            <h2 class="title">Editar Conta</h2>
            <label for="name">Nome</label>
            <div class="input">
                <i class="fa-regular fa-user"></i>
                <input type="text" name="name" id="name" value="{{ object.name }}">
            </div>
            <label for="doc">Valor</label>
            <div class="input">
                <i class="fa-solid fa-id-card"></i>
                <input type="text" name="price" id="price" value="{{ object.price }}">
            </div>
            <label for="income">Data de vencimento</label>
            <div class="input">
                <i class="fa-solid fa-sack-dollar"></i>
                <input type="date" name="due_date" id="due_date" value="{{ object.due_date }}">
            </div>
            <div id="btn">
                <a class="btn btn-secondary" href="{% url 'finance:index' %}">Voltar</a>
                <button type="submit">Salvar</button>
            </div>
        </form>
    </div>
</body>

finance/templates/index.html
<style>
    *{
    margin: 0;
    padding: 0;
    }
    body{
        width: 100%;
        height: 100%;
        font-family: 'Poppins', sans-serif;
        background: linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
    }
    .title{
        font-size: 1.8em;
        margin-bottom: 10%;
    }
    .th,td{
        width: min-content;
        border-radius: 22px;
        border: 2px #fff solid;
        padding: 5px;
        margin: 2px 2px 12px -5px;
    }
    .footer {
    font-family: 'Arial', sans-serif;
    background-color: #e5e5e5; /* Altere a cor conforme necessário */
    color: #333;
    text-align: center;
    padding: 10px 0;
    position: fixed;
    bottom: 0;
    width: 100%;
  }
  .navbar-header {
    font-family: 'Arial', sans-serif;
    background-color:transparent; /* Cor de fundo cinza escuro */
    color: #fff; /* Cor do texto branco */
    padding: 20px; /* Espaçamento interno */
  }
  .navbar-menu-header a {
    color: #fff; /* Cor do texto branco */
    margin-right: 20px; /* Espaçamento entre os itens do menu */
    text-decoration: none; /* Remover sublinhado dos links */
    font-weight: bold; /* Negrito para destacar os links */
  }
  .table{
    text-align: center;
  }
</style>
  
<header class="navbar navbar-header navbar-header-fixed">
    <div class="container-fluid">
      <a href="" id="mainMenuOpen" class="burger-menu"><i data-feather="menu"></i></a>
      <div id="navbarMenu" class="navbar-menu-wrapper">
        <div class="navbar-menu-header">
            <a href="{% url 'finance:index' %}" class="df-logo"><span>Home</span></a>
            <a href="{% url 'finance:person' %}" class="df-logo"><span>Pessoas</span></a>
            <a href="{% url 'finance:bill' %}"><span>Contas</span></a>
            <a href="{% url 'finance:person_create' %}" class="df-logo"><span>Cadastrar Pessoa</span></a>
            <a href="{% url 'finance:bill_create' %}" class="df-logo"><span>Cadastrar Conta</span></a>
        </div>
      </div> 
    </div>
</header>

<body>
    {% block content %}
    <div id="table" class="full-width">
            
        <table class="table">
            <thead class="body-title">
                <tr class= "bg-gray-200 p-2">
                    <th>Moradoes </th>
                    <th>Renda bruta</th>
                    <th>Despesa Total</th> 
                    <th>Renda Liquida</th>
                </tr>
            </thead>
            <tbody>
                {% for item in finance_data %}
                <tr>
                    <td>{{item.total_people }}</td>
                    <td>R$ {{item.total_income }}</td>
                    <td>R$ {{item.total_bill }}</td>
                    <td>R$ {{item.net_income }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endblock content %}
</body>
   
<div id="map"></div>
<footer class="footer bg-info">
    <div class="w-100">
    <span>&copy; 2024 Camilla Pinto  </span>
    </div>
</footer>

finance/templates/person.html
<style>
    *{
    margin: 0;
    padding: 0;
    }
    body{
        width: 100%;
        height: 100%;
        font-family: 'Poppins', sans-serif;
        background: linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
    }
    .title{
        font-size: 1.8em;
        margin-bottom: 10%;
    }
    .th,td{
        width: min-content;
        border-radius: 22px;
        border: 2px #fff solid;
        padding: 5px;
        margin: 2px 2px 12px -5px;
    }
    .footer {
    font-family: 'Arial', sans-serif;
    background-color: #e5e5e5; /* Altere a cor conforme necessário */
    color: #333;
    text-align: center;
    padding: 10px 0;
    position: fixed;
    bottom: 0;
    width: 100%;
  }
  .navbar-header {
    font-family: 'Arial', sans-serif;
    background-color:transparent; /* Cor de fundo cinza escuro */
    color: #fff; /* Cor do texto branco */
    padding: 20px; /* Espaçamento interno */
  }
  .navbar-menu-header a {
    color: #fff; /* Cor do texto branco */
    margin-right: 20px; /* Espaçamento entre os itens do menu */
    text-decoration: none; /* Remover sublinhado dos links */
    font-weight: bold; /* Negrito para destacar os links */
  }
  .table{
    text-align: center;
  }
</style>
  
<header class="navbar navbar-header navbar-header-fixed">
    <div class="container-fluid">
      <a href="" id="mainMenuOpen" class="burger-menu"><i data-feather="menu"></i></a>
      <div id="navbarMenu" class="navbar-menu-wrapper">
        <div class="navbar-menu-header">
            <a href="{% url 'finance:index' %}" class="df-logo"><span>Home</span></a>
            <a href="{% url 'finance:person' %}" class="df-logo"><span>Pessoas</span></a>
            <a href="{% url 'finance:bill' %}"><span>Contas</span></a>
            <a href="{% url 'finance:person_create' %}" class="df-logo"><span>Cadastrar Pessoa</span></a>
            <a href="{% url 'finance:bill_create' %}" class="df-logo"><span>Cadastrar Conta</span></a>
        </div>
      </div> 
    </div>
</header>

<body>
    {% block content %}
    <div id="table" class="full-width">
            
        <table class="table">
            <thead class="body-title">
                <tr class= "bg-gray-200 p-2">
                    <th>Nome</th>
                    <th>Documento</th>
                    <th>Renda</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for item in object_list %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.doc }}</td>
                    <td>{{ item.income }}</td>
                    <td class="action-cell">
                        <a class="btn btn-warning"title="Editar"
                            href="{% url 'finance:person_update' item.id %}">Editar
                        </a>
                        <a class="btn btn-danger"title="Deletar"
                            href="{% url 'finance:person_delete' item.id %}" style="margin-left: 15px;">Deletar
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div id="btn">
            <a class="btn btn-secondary" style="margin-left: 10px" href="{% url 'finance:index' %}">Voltar</a>
        </div>
    </div>
    {% endblock content %}
</body>
   
<div id="map"></div>
<footer class="footer bg-info">
    <div class="w-100">
    <span>&copy; 2024 Camilla Pinto  </span>
    </div>
</footer>

finance/templates/person_create.html
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght0600&display=swap');
    *{
    margin: 0;
    padding: 0;
    }
    body{
        width: 100%;
        height: 100%;
        font-family: 'Poppins', sans-serif;
        background: linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
    }
    #form{
        position: relative;
        top: 25%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: #fff ;
        border-radius: 10px ;
        padding: 60px;
        width: min-content;
        align-items: center;
        color: #2b344b;
    }
    .title{
        font-size: 1.8em;
        margin-bottom: 10%;
    }
    .input{
        min-width: 280px;
        border-radius: 22px;
        border: 2px #6f7e8a dashed;
        padding: 5px;
        margin: 0px 0px 12px -5px;
    }
    .input i{
        font-size: 1.2em;
        padding: 5px;
        background: -webkit-linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
        -webkit-background-clip: text;
        -webkit-text-fill-color:#fff ;
    }
    .input input{
        width: 80%;
        border: none;
        outline: none;
        font-family: 'Poppins', sans-serif;
        transform: translateY(-10%);
        color: #2b344b ;
        font-size: 11pt ;
    }
    #btn{
        margin-top: 10%;
        width: 100%;
        text-align: center;
    }
    #btn button{
        font-family: 'Poppins';
        background: linear-gradient(-45deg, #ffce51, #ff7253, #fd5754 );
        width: 100% ;
        height: 40px;
        border: none;
        font-size: 11pt;
        color: #fff;
        border-radius: 20px;
        outline: none;
        cursor: pointer;
    }
    
</style>

<head>
    <script src="https://kit.fontawesome.com/948cd96e81.js" crossorigin="anonymous"></script>
</head>
<body>
    <div>
        <form method="post" action="{% url 'finance:person_create' %}">
            {% csrf_token %}
            <h2 class="title">Cadastra Pessoa</h2>
            <label for="name" style="color: #fff;">Nome</label>
            <div class="input">
                <i class="fa-regular fa-user"></i>
                <input type="text" name="name" id="name" placeholder="Nome Completo" required>
            </div>
            <label for="doc" style="color: #fff;">CPF</label>
            <div class="input">
                <i class="fa-solid fa-id-card"></i>
                <input type="text" name="doc" id="cpf" placeholder="Insira seu CPF" required>
            </div>
            <label for="income" style="color: #fff;">Renda</label>
            <div class="input">
                <i class="fa-solid fa-sack-dollar"></i>
                <input type="text" name="income" id="income" placeholder="Insira sua renda mensal" required>
            </div>
            <div id="btn">
                <a class="btn btn-secondary" style="color: #fff;" href="{% url 'finance:index' %}">Voltar</a>
                <button type="submit">Salvar</button>
            </div>
        </form>
    </div>
</body>